apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payplan
resources:
  - namespace.yaml
  - ../../base
images:
  - name: ghcr.io/llstrevensll/payplan
    newTag: latest          # lo reescribe el job deploy-dev con el SHA del commit
patches:
  - path: service-nodeport.yaml
